language: python
sudo: false
python:
  - "2.7"

os:
  - linux

install:
  - ./brink.sh deps

script:
  - ./brink.sh test

after_success:
  - codecov

# Only run test when committing to master branch.
# PR tests will still be executed.
branches:
  only:
    - master
    - /\d+\.\d+.\d+/

deploy:
  provider: pypi
  user: chevah-robot
  password:
    secure: FpLpYeTSwUTKCfsAE1tXtEfN2/xBlFKnUUwxsIGXZvWhEwT6ghS1ci5YddFLxiBvgeDHLdGangmkF2wh3eUF8zZG4NYo/2lcy+vzNydLIQ3qIvHw4xDE2pqJ/1TLfyuN6gR2iB2YuvEXHDBceNxg5yXeQIZjGRdYpqprpeKBELo=
  on:
    tags: true
    all_branches: true
