language: python
python:
  - "2.7"

install:
  - pip install --extra-index-url https://pypi.chevah.com/simple -e .[dev]

script:
  - python setup.py test -q

after_success:
  - codecov

# Only run test when committing to master branch.
# PR tests will still be executed.
branches:
  only:
    - master

deploy:
  provider: pypi
  user: chevah-robot
  password:
    secure: FpLpYeTSwUTKCfsAE1tXtEfN2/xBlFKnUUwxsIGXZvWhEwT6ghS1ci5YddFLxiBvgeDHLdGangmkF2wh3eUF8zZG4NYo/2lcy+vzNydLIQ3qIvHw4xDE2pqJ/1TLfyuN6gR2iB2YuvEXHDBceNxg5yXeQIZjGRdYpqprpeKBELo=
  on:
    tags: true
    all_branches: true
