[metadata]
name = chevah-keycert
version = 3.2.0
maintainer = Adi Roiban
maintainer_email = adi.roiban@proatria.com
license = MIT
platforms = any
description = SSH Keys and SSL keys and certificates management.
long_description = file: README.rst
url = 'https://github.com/chevah/chevah-keycert'


[options]
install_requires =
    pyopenssl == 26.2.0
    cryptography == 48.0.1
    pyasn1 >= 0.1.7
    constantly >= 15.1.0
    bcrypt >= 5

packages = find:
package_dir = =src

[options.packages.find]
where = src


[options.extras_require]
; These are the deps required to develop.
; Try to pin them as much as possible.
dev =
    zope.interface
    wheel

    pocketlint ==1.4.4.c10
    pyflakes >= 3.2.0
    black == 24.2.0
    isort == 5.13.2
    psutil

    chevah-compat >= 0.70

    pynose>=1.5.4
    mock
    bunch
    coverage==7.11.3
    codecov
    unidecode
    distro
