name: GitHub-CI

on:
  push:
    branches: [ master ]
    paths:
    - '**.py'
  pull_request:
    branches: [ master ]
    paths:
    - '**.py'

permissions:
  contents: read


concurrency:
  group: chevah-keycert-${{ github.ref }}
  cancel-in-progress: true


env:
  CHEVAH_BUILD: "build-py3"

jobs:

  ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Cache build
      uses: actions/cache@v3
      with:
        path: |
          build-py3
        key: ${{ runner.os }}-${{ hashFiles('setup.py') }}

    - name: Deps
      run: |
        ./pythia.sh deps

    - name: Rename build to unicode
      run: mv build-py3 build-py3-ț

    - name: Test
      run: ./pythia.sh test
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        CHEVAH_BUILD: 'build-py3-ț'

    - name: Rename build from unicode for cache
      run: mv build-py3-ț build-py3


  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache build
      uses: actions/cache@v3
      with:
        path: |
          build-py3
        key: ${{ runner.os }}-${{ hashFiles('setup.py') }}

    - name: Deps
      run: ./pythia.sh deps

    - name: Test
      run: ./pythia.sh test
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache build
      uses: actions/cache@v3
      with:
        path: |
          build-by3
        key: ${{ runner.os }}-${{ hashFiles('setup.py') }}

    - name: Deps
      run: sh ./pythia.sh deps

    - name: Test
      run: sh ./pythia.sh test
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  keys-interop:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - { test_type: "--load dsa" }
          - { test_type: "--load rsa" }
          - { test_type: "--load ecdsa" }
          - { test_type: "--load ed25519" }
          - { test_type: "--generate" }
    steps:
    - uses: actions/checkout@v4

    - name: Cache build
      uses: actions/cache@v3
      with:
        path: |
          build-py3
        key: ${{ runner.os }}-${{ hashFiles('setup.py') }}

    - name: Deps
      run: |
        sudo apt-get --quiet install putty-tools
        ./pythia.sh deps

    - name: Test
      run: ./pythia.sh test_interop ${{ matrix.config.test_type }}

  lint:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Cache build
      uses: actions/cache@v3
      with:
        path: |
          build-py3
        key: ${{ runner.os }}-${{ hashFiles('setup.py') }}

    - name: Deps
      run: |
        ./pythia.sh deps

    - name: Lint
      run: ./pythia.sh lint
