name: GitHub-CI

on:
  push:
    branches: [ master ]
    paths:
    - '**.py'
  pull_request:
    branches: [ master ]
    paths:
    - '**.py'

jobs:

  linux-unicode-path:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Deps
      run: ./brink.sh deps

    - name: Test
      run: ./brink.sh test_ci
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  osx-unicode-path:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deps
      run: ./brink.sh deps

    - name: Test
      run: ./brink.sh test_ci
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deps
      run: sh ./brink.sh deps

    - name: Test
      run: sh ./brink.sh test_ci
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
